version: '3.8'

services:
  pmb-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app    
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    #start:dev does not work inside container, workaround is to use nodemon
    command: yarn start:dev